module.exports = {
  coveragePathIgnorePatterns: ['/__tests__/', '/node_modules/'],
  // roots: [
  //   '<rootDir>/src',
  //   '<rootDir>/tests',
  // ],
  collectCoverage: true,
  verbose: true,
  testEnvironment: 'node',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'core', 'node'],
  cacheDirectory: '.jest/cache',
  coverageDirectory: 'coverage',
  coverageReporters: ['text-summary', 'html'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/lib/',
    '/dist/',
    '/integration-tests/',
    '\\.snap$',
    '/build/',
    '/coverage/',
    '/packages/.*/build',
    '/packages/.*/dist',
    '/packages/.*/lib',
  ],
  // testMatch: ['<rootDir>/packages/**/*.spec.js'],
}
